version: "3"
services:
    db:
        build: .
        image: postgres:alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        secrets:
            - ro-database
            - rw-database
        ports:
            - 5432:5432
        volumes:
            - ./db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    supplier-job:
        build: supplier-service/
        image: suplier-service:latest
        depends_on:
            - db
        links:
            - db
        secrets:
            - rw-database
            - supplier-service

secrets:
    ro-database:
        file: ./secrets/ro-database
    rw-database:
        file: ./secrets/rw-database
    supplier-service:
        file: ./secrets/supplier-service
            