spring:
  main:
    web-application-type: NONE

  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}"
    username: "${DB_USER}"
    password: "${DB_PASS}"

  flyway:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}"
    user: "${DB_USER}"
    password: "${DB_PASS}"
    validate-on-migrate: true
    enabled: true

integration:
  supplier:
    url: "${SUPPLIER_URL}"
    connection-timeout: 15000
