server:
  port: 8000

spring:

  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=authorization-server"
    username: "${DB_USER}"
    password: "${DB_PASS}"

  flyway:
    url: "jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}"
    default-schema: "authorization-server"
    user: "${DB_USER}"
    password: "${DB_PASS}"
    validate-on-migrate: true
    enabled: true

leuras:
  jwt:
    access-token:
      secret: "${ACCESS_TOKEN_SECRET}"
      expiration: 3600000 # 1 hour
    refresh-token:
      secret: "${REFRESH_TOKEN_SECRET}"
      expiration: 5184000000 # 60 days